### ISSUE TITLE
avr/dtostrf.h: No such file or directory

### ISSUE THREAD

**Issue by dwblair** [plotly/arduino-api#3]
Hi All,

When compiling using the Arduino IDE 1.0.5 on Ubuntu 13.10, and using the plotly_ethernet code, I get the following error:

C:\arduino-1.5.3\libraries\plotly_ethernet\plotly_ethernet.cpp:1:25: fatal error: avr/dtostrf.h: No such file or directory
compilation terminated.

There's a thread online about this issue:
http://forum.arduino.cc/index.php/topic,211656.0.html

I fixed the problem for myself by adding the "dtostrf" function directly at the end of my local copy of plotly_ethernet.cpp, as in the following gist:

https://gist.github.com/dwblair/9235676

Don't know if that's the most elegant / useful fix (or maybe I'm doing something else wrong, and this won't be an issue for other people) ...

Cheers!

**Comment by sheepsblood** [comment]
Changed your API's? 
What does that have to do exactly with this error?
Because, I am using the most recent GIT for PLOTLY and it still throws this error.

How about a resolution to this issue.

It's nearly a year later.

**Comment by alexander-daniel** [comment]
@sheepsblood

I tried the following and was able to get it to work, let me know if this works for you.

Clone the Plotly-Arduino Repository.
`git clone https://github.com/plotly/arduino-api.git`

Copy the folders inside to ~/Documents/Arduino/libraries
(You can copy only the ones you want, I only copied Ethernet)
![screen shot 2015-02-23 at 12 16 47 pm](https://cloud.githubusercontent.com/assets/5408720/6332715/79327c68-bb55-11e4-8e2f-f802e5674d57.png)

Open a new sketch and copy the following into it: (This is the ethernet + plotly example)
https://raw.githubusercontent.com/plotly/arduino-api/master/examples/ethernet/simple_ethernet.ino

Change the `api_key` + `tokens` in that example.

Using 1.0.3 and 1.0.6. Please keep me posted.

**Comment by sheepsblood** [comment]
Thanks Alexander, I will try that today and let you know my outcome.

**Comment by alexander-daniel** [comment]
Great, thanks!

**Comment by sheepsblood** [comment]
I was excited to get your help so I went and did what you said, step by step. IT WORKS !!!
Thank you so much!!!
I have been so frustrated trying to figure out what the deal was. At least I have another few ideas up my sleeve to use towards tackling issues like this in the future!
Again, THANK YOU!!!

**Comment by alexander-daniel** [comment]
:smile: Amazing! I'm so glad it worked. Feel free to open an Issue if you run into things in the future!

Cheers!

**Comment by technodict** [comment]
will the above solution work for the GSM sketch ? i am getting the following error 

/usr/share/arduino/libraries/plotly_streaming_gsm/plotly_streaming_gsm.cpp:5:25: fatal error: avr/dtostrf.h: No such file or directory
 #include <avr/dtostrf.h>
                         ^
compilation terminated.

**Comment by vicatcu** [comment]
This seems to be an issue in arduino 1.6.0. Probably related to changes in the avr-gcc toolchain. Should I open a new issue?

**Comment by alexander-daniel** [comment]
@vicatcu that would be great! thanks

**Comment by hohokam337** [comment]
Mate, I having the same issue Arduino 1.6.10 **#include <avr/dtostrf.h> Not found**
