### ISSUE TITLE
... Attempting to resolve IP address of plot.ly

### ISSUE THREAD

**Issue by drrehak** [plotly/arduino-api#31]
using 
firmware 1.14 on CC3000 wifi shield
arduino IDE 1.0.6

the serial monitor hangs with:
... Attempting to resolve IP address of plot.ly

I would appreciate any ideas or next steps for troubleshooting.  Thanks!

**Comment by thepatman** [comment]
There are at least two bugs in the library.
Open plotly_streaming_cc3000.cpp in an editor and edit line 45
remove \n from the end of the host name.
i.e.
From :  
`if (! cc3000.getHostByName("www.plot.ly\n", &ip)) {`
To:  
`if (! cc3000.getHostByName("www.plot.ly", &ip)) {`

The ip address should then resolve.

The library will hang later on unless you move client.close() on line 147 to inside the if(client.available()) function.

i.e.

From
```
if(!dry_run){
    char c;
    while(client.connected()){
        if(client.available()){
            c = client.read();

            Serial.print(c);
        }
    }
    client.close();
}
return true;
```

To
```
if(!dry_run){
    char c;
    while(client.connected()){
        if(client.available()){
            c = client.read();

            Serial.print(c);
            client.close();
        }
    }
}
return true;
```

With client.close() outside the function it's effectively a while(true) loop.

Hope this helps.

**Comment by drrehak** [comment]
thank you!!!!!  yes, it all works perfectly now.  You rock!  I need to buy you a beer!

**Comment by waaraawa** [comment]
thepatman

Your codes are work for wifi also.
Thanks
