### ISSUE TITLE
No such file or directory compilation terminated. Error compiling.

### ISSUE THREAD

**Issue by sheepsblood** [plotly/arduino-api#32]
fatal error: plotly_streaming_ethernet.h: No such file or directory compilation terminated. Error compiling.

#include <Ethernet.h>
#include <SPI.h>
#include "plotly_streaming_ethernet.h"

I recently downloaded the Plotly Arduino Library and tried incorporating it to my Arduino Mega 2560. I also have the W5200  V.2 Ethernet Shield by seeedstudio piggy backed to it. I am connected via /dev/tty.usbmodem and programmer is set to USBtinyISP.

My issue is finding a resolution to an issue I am having. I receive this error whenever I compile...

/*
fatal error: plotly_streaming_ethernet.h: No such file or directory
compilation terminated.
Error compiling. 

*/

I have searched the Internet for those who may have had similar issues. 

Yes, I added the library properly 
Yes, I have an updated version of the Arduino IDE. 
Yes, I have restarted both my Mac & the IDE
Yes, I have uninstalled Arduino IDE and removed all traces of it and then reinstalled the software. (same with plotly library)

**Comment by sheepsblood** [comment]
I solved part of it...
Unlike usual placement of Arduino files "~Documents/Arduino/libraries/arduino-api-master"
I had to place all sub folders into "~Documents/Arduino/libraries"

Now I have another issue...

Documents/Arduino/libraries/plotly_streaming_ethernet/plotly_streaming_ethernet.cpp:6:25: fatal error: avr/dtostrf.h: No such file or directory
 #include <avr/dtostrf.h>
                         ^
compilation terminated.
Error compiling.

**Comment by sheepsblood** [comment]
Closed

**Comment by andershf** [comment]
Hi

Did you solve the problem? I get the same error.

**Comment by alexander-daniel** [comment]
@andershf https://github.com/plotly/arduino-api/issues/3

**Comment by LeeHewitt** [comment]
same problem....

**Comment by alexander-daniel** [comment]
I'll take another look at this tomorrow AM. For now, can you try using an older version of the Arduino IDE?

I get pretty good results using 1.0.3

I'll be in touch tomorrow!

**Comment by mowoe** [comment]
When you are unpacking the zo file, most programs put the folder into another folder.
when you take the folder in the folder to the libraries folder, all is working(by me)
sorry for my bad english im from germany

**Comment by C-Low3** [comment]
Files need to be unzipped into your Arduino library folder
