### ISSUE TITLE
#include <avr/dtostrf.h> No such file or directory

### ISSUE THREAD

**Issue by sheepsblood** [plotly/arduino-api#34]
When using the plotly_streaming_ethernet example I receive this error.

Again, much time spent researching it and testing several methods for a resolution and none have worked so far.

Documents/Arduino/libraries/plotly_streaming_ethernet/plotly_streaming_ethernet.cpp:6:25: fatal error: avr/dtostrf.h: No such file or directory
 #include <avr/dtostrf.h>
                         ^
compilation terminated.
Error compiling.

There is a suggestion for a fix but it doesn't work ( http://forum.arduino.cc/index.php/topic,211656.0.html )

Oh, and if you exclude <avr/dtostrf.h> , the compiler blows up with lots of problems. (maybe obviously, but they are pointing out double declarations such as "plotly: ploty"

**Comment by alexander-daniel** [comment]
@sheepsblood 
Referenced here: https://github.com/plotly/arduino-api/issues/3
