### ISSUE TITLE
Data values getting sometimes plotted at the wrong timestamp or the wrong chart.

### ISSUE THREAD

**Issue by jimconner** [plotly/arduino-api#49]
This is something of a strange issue, and is actually affecting the Electric Imp rather than Arduino, but I think they're both using the same API so I'm raising the issue here. I've spent many hours trying to work out what's going wrong and I'm pretty much convinced now that the problem is not with my code (which can be found at https://github.com/jimconner/greenhouse_monitoring/tree/lux_pressure ). My code is loosely based upon the example plotly Electric Imp tmp36 tutorial ( https://plot.ly/electric-imp/tmp36-temperature-tutorial/ ), but has been extended as I've added more and more sensors to monitor. I'm now logging six different temperature sensors, plus air pressure and light levels.

My code used to work just fine back in January/February when I only had five temperature sensors attached, but the battery ran out on my Imp back in February so I hadn't attempted to log any data in the intervening months - When I powered the Imp back up again last week, I discovered some oddness in the plots.

I am sending sensor readings to plot.ly once per minute, and for the first 3-5 minutes, data appears on the plot as expected, but after a few minutes things seem to get rather confused. Readings seem to be getting logged into the wrong timestamp positions such that any given minute on the plot may show multiple readings from the same sensor. Some sensors are still plotting at the correct time values, but others get overlayed. In Grid view, somehow or other multiple sensors are getting combined into a single colume value (i.e. I'll have a column labelled "Ambient_Temperature,Water_Temperature"). To add to the confusion, sometimes the sensor values are not being logged to the correct plot at all, and instead I find that I have gained some new 'Grid xxx' objects in my workspace which contain a random collection of sensor readings.

I've logged the api requests I'm sending through, and every one of them looks perfect - The timestamp format is all correct, the sensors all have their 'name' field set correctly. The plotly layout object is sent along with each api request, detailing the plot title and filename, but somehow or other the data isn't ending up on the correct plot.

It's a weird weird problem which I am unable to explain - it's as if the data I'm sending through to plotly is not being sorted to the correct plot/timestamp as I'd expect.

Any insight you can offer would be greatly appreciated. I'm available to make modifications to my code, run tests, debug etc in whatever way I can help.

**Comment by paulcounter** [comment]
This sounds very much like the long term issue I have had. I have even gone
to the extent of creating false time stamps so I could ensure that I knew
the exact values. Even then the data were recorded at the wrong time.

**Comment by alexander-daniel** [comment]
@jimconner Can you paste your imp Server and Agent nuts into a gist? I'd like to take a peek. Thanks!

**Comment by alexander-daniel** [comment]
@jimconner I'll take a look, thanks for providing your code. It's even weirder that the Imp is doing this, as its hitting a totally different endpoint than the Arduino.

**Comment by jimconner** [comment]
Thanks for looking into this @alexander-daniel - If there's anything I can do to help, give me a shout.

**Comment by jimconner** [comment]
I've been messing around with my electricimp again today, and whatever the problem was back in June appears to have been fixed now. Nothing's changed in my code, so I know it wasn't that... Anyway.. as the issue is now fixed, I'm going to close this.
